---
title: "Class Activity, January 11"
output: 
  tufte::tufte_html:
    css: "lab.css"
    tufte_variant: "envisioned"
    highlight: pygments
link-citations: yes
---

In this activity, we will work with the fitted logistic regression model from the dengue data. The fitted logistic regression model is 

$$\hspace{1cm} Y_i \sim Bernoulli(\pi_i)$$
$$\hspace{1cm} \log \left( \dfrac{\widehat{\pi}_i}{1 - \widehat{\pi}_i} \right) = -2.45 + 0.22 \ Age_i$$

# Questions

1. Does the probability of dengue increase or decrease with age?

<SCRIPT>
function ShowAndHide(divid) {
    var x = document.getElementById(divid);
    if (x.style.display == 'none') {
        x.style.display = 'block';
    } else {
        x.style.display = 'none';
    }
}
</SCRIPT>

<BUTTON ONCLICK="ShowAndHide('q1_solution')">Solution</BUTTON>

<DIV ID="q1_solution" STYLE="display:none">
The slope of the fitted model (0.22) is positive, which means that the log odds increase as age increases. Therefore the probability also increases as age increases.
</DIV>

2. What is the predicted odds of dengue for a 5 year old patient?


3. Based on your answer to question 2, for a 5 year old patient is the predicted *probability* of dengue $> 0.5$, $< 0.5$, or $= 0.5$? (You should answer this without performing any calculations).

4. Now calculate the predicted *probability* of dengue for a 5 year old patient.
